version: '3.1'
services :
  db:
    image: postgres:10-alpine
    container_name: ${DB_NAME}-db
    restart: unless-stopped
    ports:
      - "5432:${DB_PORT}"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
  adminer:
    image: adminer
    container_name: ${DB_NAME}-adminer
    restart: unless-stopped
    depends_on: 
      - db
    ports:
      - 8080:8080