@port = 5000
@baseURL = http://127.0.0.1:{{port}}/api

## Home
# GET {{baseURL}}

## GET users
GET {{baseURL}}/users/6fec9ba6-cf96-480b-9cdd-bb9b3f9e937b

## POST user
POST {{baseURL}}/users
Content-Type: application/json

{
    "username": "Adolfo Alvarez",
    "email": "aeap@gmail.com",
    "password": "passWORD1998!"
}