@port = 5000
@baseURL = http://127.0.0.1:{{port}}/api

### Home
GET {{baseURL}}

### GET users
GET {{baseURL}}/users?sort=email

### POST signup
POST {{baseURL}}/auth/signup
Content-Type: application/json

{
    "username": "Adolfo Pacheco",
    "email": "apacheco@gmail.com",
    "password": "aeAP1998!"
}

### POST signin
POST {{baseURL}}/auth/signin
Content-Type: application/json

{
    "username": "Adolfo Pacheco",
    "password": "aeAP1998!"
}

### POST roles
POST {{baseURL}}/roles
Content-Type: application/json

{
    "name": "ADMIN",
    "description": "Administrator role with all permissions"
}